In [1]:
import numpy as np
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [2]:
array =np.zeros( (2,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
array =np.ones( (1,5) )
print(array)

[[1. 1. 1. 1. 1.]]


In [4]:
n = int(input("kaç adet sayı girilecek : "))
a=[]
for i in range(0,n):
    elem=int(input("sayiyi girin : "))
    a.append(elem)
avg = sum(a)/n
print("girilen sayıların ortalaması: ",round(avg,2))

kaç adet sayı girilecek : 3
sayiyi girin : 1
sayiyi girin : 7
sayiyi girin : 6
girilen sayıların ortalaması:  4.67
